apiVersion: v1
kind: Service
metadata:
  name: caddy-service
  labels:
    app: caddy
spec:
  selector:
    app: caddy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
    - protocol: TCP
      port: 443
      targetPort: 443
      name: https
  type: LoadBalancer
