apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: live-tv
  namespace: argocd
spec:
  project: default
  source:
    # TODO: update repoURL when pushing to Git
    repoURL: https://github.com/YOUR_ORG/live-tv
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: live-tv
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
